### ISSUE TITLE
webpack-dev-server won't run

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [angular-class/angular2-webpack-starter#41]
I'm getting the following when I run `npm run server`
I couldn't find any open issues with webpack or webpack-dev-server.  Also, nothing is jumping out at me in the webpack config.

```
Dans-MBP:angular2-webpack-starter dan$ npm run server

> angular2-webpack-starter@0.0.0 server /Users/dan/Projects/js/angular2-webpack-starter
> webpack-dev-server --inline --colors --display-error-details --display-cached 

/Users/dan/Projects/js/angular2-webpack-starter/node_modules/webpack/node_modules/tapable/lib/Tapable.js:164
		arguments[i].apply(this);
		            ^
TypeError: Cannot read property 'apply' of undefined
    at Tapable.apply (/Users/dan/Projects/js/angular2-webpack-starter/node_modules/webpack/node_modules/tapable/lib/Tapable.js:164:15)
    at OptionsApply.WebpackOptionsApply.process (/Users/dan/Projects/js/angular2-webpack-starter/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/Users/dan/Projects/js/angular2-webpack-starter/node_modules/webpack/lib/webpack.js:22:48)
    at Object.<anonymous> (/Users/dan/Projects/js/angular2-webpack-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:133:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@0.0.0 server: `webpack-dev-server --inline --colors --display-error-details --display-cached `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@0.0.0 server script 'webpack-dev-server --inline --colors --display-error-details --display-cached '.
npm ERR! This is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --colors --display-error-details --display-cached 
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dan/Projects/js/angular2-webpack-starter/npm-debug.log
```

**Comment by gdi2290** [comment]
@Blackbaud-DanHamlin could you delete `node_modules/` and install it again. In the meantime you can use the express server with `npm run express` but make sure you install the deps first with `npm run express-install`

**Comment by Blackbaud-DanHamlin** [comment]
Thanks, express did work.  Removing node_modules and reinstalling didn’t fix my problem with webpack.

**Comment by noxxious** [comment]
I found the culprit - it seems that if NODE_ENV is not defined, then the environment plugins lookup produce a null to the plugins array in the webpack.config.js. Adding the definition to explicity default to development if NODE_ENV is not defined fixed it.

**Comment by gdi2290** [comment]
@noxxious thanks for looking into it :+1:  can you make a Pull-Request?
```es6
var NODE_ENV = process.env.NODE_ENV || 'development';
```

**Comment by Blackbaud-DanHamlin** [comment]
great, i wonder if those npm scripts for setting the environment aren't actually working then?

**Comment by gdi2290** [comment]
@noxxious you can make a pull-request simply just by clicking edit icon either on desktop or mobile 
<img width="591" alt="screen shot 2015-07-29 at 2 58 45 pm" src="https://cloud.githubusercontent.com/assets/1016365/8971085/5da32b28-3602-11e5-80b4-1008577d4c34.png">

**Comment by gdi2290** [comment]
fixed via https://github.com/angular-class/angular2-webpack-starter/pull/43
